const test = require('node:test');
const assert = require('node:assert/strict');
const { validateRequest, runTool, collectData } = require('../services/chatData');
const { sourcesFor, answerQuestion } = require('../services/chat');
test('rejects arbitrary tools, SQL, identity overrides and invalid filters', () => {
  for (const request of [
    { tool: 'sql', args: { sql: 'SELECT * FROM users' } },
    { tool: 'finance', args: { userId: 'victim' } },
    { tool: 'finance', args: { groupBy: 'constructor' } },
    { tool: 'finance', args: { sort: 'DROP TABLE users' } },
    { tool: 'finance', args: { startDate: '2026-02-30' } },
    { tool: 'finance', args: { offset: -1 } },
  ])
    assert.throws(() => validateRequest(request));
});
test('financial queries use bound identity and literal search parameters', async () => {
  const calls = [];
  const client = {
    query: async (sql, params) => {
      calls.push({ sql, params });
      return { rows: sql.includes('first_date') ? [{ transaction_count: '0' }] : [] };
    },
  };
  await runTool(client, 'owner', {
    tool: 'finance',
    args: { search: "%' OR 1=1 --", groupBy: 'category' },
  });
  assert.equal(calls.length, 3);
  for (const call of calls) {
    assert.equal(call.params[0], 'owner');
    assert.match(call.sql, /t.user_id=\$1/);
    assert.ok(!call.sql.includes('OR 1=1'));
    assert.ok(call.params[1].includes('OR 1=1'));
  }
});
test('retrieval runs inside a read-only snapshot and releases on failure', async () => {
  const calls = [];
  let released = false;
  const client = {
    query: async (sql) => {
      calls.push(sql);
      return { rows: [] };
    },
    release: () => {
      released = true;
    },
  };
  await assert.rejects(() =>
    collectData({ connect: async () => client }, 'owner', [{ tool: 'sql' }]),
  );
  assert.match(calls[0], /READ ONLY/);
  assert.equal(calls.at(-1), 'ROLLBACK');
  assert.ok(released);
});
test('profile query excludes password, tokens and secrets', async () => {
  let sql;
  await runTool(
    {
      query: async (value) => {
        sql = value;
        return { rows: [] };
      },
    },
    'owner',
    { tool: 'profile' },
  );
  assert.doesNotMatch(sql, /password|token|secret|SELECT \*/i);
  assert.match(sql, /WHERE id=\$1/);
});
test('activity tool accepts valid filters and excludes passwords/secrets', async () => {
  const req = validateRequest({
    tool: 'activity',
    args: { action: 'PASSWORD_CHANGE', limit: '10' },
  });
  assert.equal(req.tool, 'activity');

  const executedQueries = [];
  const fakeClient = {
    query: async (sql, params) => {
      executedQueries.push({ sql, params });
      return { rows: [] };
    },
  };
  const result = await runTool(fakeClient, 'owner-id', { tool: 'activity' });
  assert.equal(result.tool, 'activity');
  assert.ok(result.summary);
  assert.equal(result.summary.password_changes_count, 0);
  for (const q of executedQueries) {
    assert.doesNotMatch(q.sql, /password_hash|token_version|secret|SELECT \* FROM users/i);
    assert.match(q.sql, /WHERE user_id = \$1/);
  }
});
test('source URLs are generated by the server, not by model text', () => {
  const sources = sourcesFor([
    {
      tool: 'statements',
      data: [
        { id: 'https://malicious.example', file_name: 'Fake' },
        { id: '00000000-0000-0000-0000-000000000001', file_name: 'Real' },
      ],
    },
    { tool: 'activity' },
  ]);
  assert.equal(sources.length, 3);
  assert.ok(sources.every((s) => s.href.startsWith('/')));
  const activitySource = sources.find((s) => s.id === 'activity');
  assert.ok(activitySource);
  assert.equal(activitySource.href, '/activity');
});
test('assistant uses retrieved evidence and drops invented sources', async () => {
  const queries = [];
  const client = {
    query: async (sql) => {
      queries.push(sql);
      return { rows: [] };
    },
    release() {},
  };
  let call = 0;
  const generate = async (prompt) => {
    call++;
    if (call === 1) return { requests: [{ tool: 'product' }] };
    assert.match(prompt, /No refund management/);
    assert.match(prompt, /Uploaded statement files and personal AI keys are protected at rest/);
    assert.match(prompt, /mobile application for iOS and Android/);
    assert.match(prompt, /fully integrated with WhatsApp/);
    assert.match(prompt, /saved as a pending draft/);
    return {
      answer: 'Use Statements to delete a statement.',
      sourceIds: ['product', 'https://evil.example'],
    };
  };
  const result = await answerQuestion(
    { connect: async () => client },
    'owner',
    'How do I delete?',
    [],
    { providerId: 'gemini', model: null, apiKey: null },
    generate,
  );
  assert.equal(result.sources.length, 1);
  assert.equal(result.sources[0].id, 'product');
});

test('assistant provides accurate context for mobile app and whatsapp feature queries', async () => {
  const client = {
    query: async () => ({ rows: [] }),
    release() {},
  };
  let call = 0;
  const generate = async (prompt) => {
    call++;
    if (call === 1) return { requests: [{ tool: 'product' }] };
    assert.match(prompt, /React Native and Expo/);
    assert.match(prompt, /WhatsApp/);
    assert.match(prompt, /Cost Transparency/);
    return {
      answer:
        'Yes, Finlytix provides a native mobile app for iOS and Android built with React Native and Expo.',
      sourceIds: ['product'],
    };
  };
  const result = await answerQuestion(
    { connect: async () => client },
    'owner',
    'Do we have any mobile app?',
    [],
    { providerId: 'gemini', model: null, apiKey: null },
    generate,
  );
  assert.equal(result.sources.length, 1);
  assert.equal(result.sources[0].id, 'product');
  assert.ok(result.answer.includes('iOS and Android'));
});
