const test = require('node:test');
const assert = require('node:assert/strict');
const { validateRequest, runTool, collectData } = require('../services/chatData');
const { sourcesFor, answerQuestion } = require('../services/chat');
test('rejects arbitrary tools, SQL, identity overrides and invalid filters', () => {
  for (const request of [
    { tool: 'sql', args: { sql: 'SELECT * FROM users' } },
    { tool: 'finance', args: { userId: 'victim' } },
    { tool: 'finance', args: { groupBy: 'constructor' } },
    { tool: 'finance', args: { sort: 'DROP TABLE users' } },
    { tool: 'finance', args: { startDate: '2026-02-30' } },
    { tool: 'finance', args: { offset: -1 } },
  ])
    assert.throws(() => validateRequest(request));
});
test('financial queries use bound identity and literal search parameters', async () => {
  const calls = [];
  const client = {
    query: async (sql, params) => {
      calls.push({ sql, params });
      return { rows: sql.includes('first_date') ? [{ transaction_count: '0' }] : [] };
    },
  };
  await runTool(client, 'owner', {
    tool: 'finance',
    args: { search: "%' OR 1=1 --", groupBy: 'category' },
  });
  assert.equal(calls.length, 3);
  for (const call of calls) {
    assert.equal(call.params[0], 'owner');
    assert.match(call.sql, /t.user_id=\$1/);
    assert.ok(!call.sql.includes('OR 1=1'));
    assert.ok(call.params[1].includes('OR 1=1'));
  }
});
test('retrieval runs inside a read-only snapshot and releases on failure', async () => {
  const calls = [];
  let released = false;
  const client = {
    query: async (sql) => {
      calls.push(sql);
      return { rows: [] };
    },
    release: () => {
      released = true;
    },
  };
  await assert.rejects(() =>
    collectData({ connect: async () => client }, 'owner', [{ tool: 'sql' }]),
  );
  assert.match(calls[0], /READ ONLY/);
  assert.equal(calls.at(-1), 'ROLLBACK');
  assert.ok(released);
});
test('profile query excludes password, tokens and secrets', async () => {
  let sql;
  await runTool(
    {
      query: async (value) => {
        sql = value;
        return { rows: [] };
      },
    },
    'owner',
    { tool: 'profile' },
  );
  assert.doesNotMatch(sql, /password|token|secret|SELECT \*/i);
  assert.match(sql, /WHERE id=\$1/);
});
test('source URLs are generated by the server, not by model text', () => {
  const sources = sourcesFor([
    {
      tool: 'statements',
      data: [
        { id: 'https://malicious.example', file_name: 'Fake' },
        { id: '00000000-0000-0000-0000-000000000001', file_name: 'Real' },
      ],
    },
  ]);
  assert.equal(sources.length, 2);
  assert.ok(sources.every((s) => s.href.startsWith('/')));
});
test('assistant uses retrieved evidence and drops invented sources', async () => {
  const queries = [];
  const client = {
    query: async (sql) => {
      queries.push(sql);
      return { rows: [] };
    },
    release() {},
  };
  let call = 0;
  const generate = async (prompt) => {
    call++;
    if (call === 1) return { requests: [{ tool: 'product' }] };
    assert.match(prompt, /No refund management/);
    return {
      answer: 'Use Statements to delete a statement.',
      sourceIds: ['product', 'https://evil.example'],
    };
  };
  const result = await answerQuestion(
    { connect: async () => client },
    'owner',
    'How do I delete?',
    [],
    'gemini',
    generate,
  );
  assert.equal(result.sources.length, 1);
  assert.equal(result.sources[0].id, 'product');
});
