// Product knowledge is intentionally curated: do not send repository files,
// environment configuration, or credentials to the model.
module.exports = {
  faqs: require('../data/faqs.json'),
  version: '2026-09-13',
  aiUseCaseSettings:
    'On the web, Settings > AI Models & Keys offers independent provider/model/key settings for text chat, voice answers, statement extraction, transaction categorization, bill extraction, and WhatsApp chat. Each requires its own provider/model and an explicitly selected platform key or encrypted personal key; there are no shared defaults. Models are limited to the administrator catalogue. Voice transcription and playback use browser speech, not a Gemini Live model. Missing dedicated or saved keys do not fall back to platform billing. Validate & save checks model access with a small synthetic prompt before saving and may consume provider quota. Failed validation preserves previous settings. Changes apply to the next operation without restart; running requests retain their original connection.',
  purpose:
    'Finlytix analyses uploaded Indian bank statements. It has no live connection to bank accounts.',
  mobileApp:
    'Finlytix provides a production-ready, full-featured cross-platform native mobile application for iOS and Android built with React Native and Expo (under mobile/). The mobile app has 100% feature parity with the web dashboard, allowing users to view spending analytics, upload statements, review transactions, manage categories, configure settings, and chat with Finlytix AI. Native mobile capabilities include Face ID / Touch ID / Fingerprint biometric authentication (expo-local-authentication), hardware-backed encrypted keychain token storage (expo-secure-store), camera receipt scanning (expo-image-picker), document picker for PDF & XLSX bank statements (expo-document-picker), pull-to-refresh live synchronization, and offline-safe state management sharing core business logic via @finlytix/shared.',
  whatsappIntegration:
    'Finlytix features native integration with WhatsApp (via Meta WhatsApp Cloud API and Twilio transport). Key capabilities: 1) Document Ingestion: Users can upload or forward bank statements (PDF or XLSX) directly to the Finlytix WhatsApp bot with optional captions (e.g., "HDFC Jan 2026"). AI extracts transactions, creates a draft, and replies with an interactive WhatsApp card containing action buttons: [Confirm & Import], [View Summary], and [Discard]. Confirming commits transactions directly into the live ledger. 2) Passwordless login and phone number verification using single-use 6-digit WhatsApp OTPs and 1-tap Magic Links. 3) Ask Finlytix AI Copilot natively inside WhatsApp chat, allowing users to query spending, category totals, net cash flow, and top transactions directly in WhatsApp.',
  costTransparency:
    'In commitment to user information rights and radical transparency, Finlytix provides a dedicated "Cost Transparency & Resource Footprint" section in Settings on both Web and Mobile. It displays an itemized breakdown of cloud infrastructure costs incurred to serve each user: AI multimodal statement parsing, transaction categorisation, AI copilot chat messages, encrypted file vault storage, and PostgreSQL ledger compute. When users bring their own AI key (BYOK mode), platform AI cost is strictly $0.00 / ₹0.00 with an active "Personal Key Active — Zero Platform AI Cost" badge. All costs dynamically convert to the user\'s configured currency.',
  banks:
    'Settings lets users search a central catalogue of 80 domestic Indian banks. Cooperative banks are not yet included. Remove only with no statements; otherwise deactivate. Reactivation restores upload availability. Catalogue updates are reviewed manually using RBI sources.',
  imports:
    'Select an active saved bank, year/month and PDF or XLSX (10 MB maximum). AI extracts transactions; review before confirming. One statement per user/bank/month across formats. Invalid dates or any transaction outside the selected month reject the import. Extraction can be imperfect: compare the preview with the original. In addition to web and mobile uploads, statements can be forwarded directly via WhatsApp.',
  management:
    'Statements offers preview of extracted transactions, download of retained originals for new uploads, and delete. Older originals were not retained. Deleting cascades to transactions, drafts, attached bills, line items and retained original; totals refresh and the month becomes available again.',
  categories:
    'Settings manages parent categories and subcategories. Transactions supports manual category corrections and AI suggestions. Automatic learning from corrections is not implemented.',
  analytics:
    'Dashboard shows credits as income, debits as expenses, net cash flow and savings rate. Analytics supports date ranges and category, monthly and trend charts. Net cash flow is not a bank balance. Transfers are not automatically reconciled across banks, so they can inflate income/expense. Only imported transactions count; pending review statements do not count.',
  bills:
    'Users can attach merchant bills to transactions and review extracted line items. Bills provide detail; do not add bill amounts to transaction totals again. On mobile devices, bills and receipts can be scanned directly using the camera.',
  account:
    'Email/password signup with email verification, and WhatsApp passwordless OTP/magic link login with phone number verification. Account profile, personal AI keys, notification preferences, bank catalogue, and cost footprint are unified in the Settings hub on web and mobile. Credentials, tokens and other users are never available to this assistant.',
  assistant:
    'Read-only financial and product assistant. Can query own transactions, summaries, categories, banks, statement coverage, profile, attached bills and application payment history. Cannot upload, delete, change categories, send messages or execute payments. Chat history is saved to the user account. The user can load older messages or permanently delete saved history using the assistant page controls. Uses the configured AI provider; relevant retrieved data is sent to it.',
  techArchitecture:
    'Finlytix is engineered as a privacy-first personal financial intelligence platform. Frontend: Next.js App Router, React, TypeScript, Tailwind CSS, plus cross-platform React Native Expo apps for iOS and Android. Backend: Node.js with Express and PostgreSQL relational database with connection pooling and strict schema constraints. Security & Cryptography: Application-level authenticated encryption using AES-256-GCM (96-bit initialization vector and 128-bit authentication tag) secures both uploaded statement files and user personal BYOK API keys at rest. Plaintext keys never leave the server; masked previews only. Passwords use bcrypt hashing (12 salt rounds), and JWT sessions utilize per-user token versions for instant multi-device revocation. Statement Ingestion Pipeline: Multimodal and structured schema extraction using Google Gemini and Anthropic Claude; strict calendar month boundary validation, duplicate statement prevention, and draft reconciliation workflow before ledger commit. Analytics Engine: Relational PostgreSQL aggregation for multi-currency ISO 4217 cash flow, category budgets, savings rate, and customizable date/time formatters. Privacy & Data Minimization: Zero financial data queries in admin telemetry, automatic PII scrubbing on crash reports (redacting JWTs, auth headers, bank account numbers, emails), full GDPR/DPDP-compliant JSON archive and vector PDF exports, and one-click cryptographic account deletion with foreign key cascading.',
  security:
    'Uploaded original bank statement files and personal AI keys are protected at rest using application-level authenticated AES-256-GCM encryption with separately managed server keys. Personal BYOK keys are never stored in plaintext and never leave the server; only masked previews are shown. Zero-fallback protection guarantees personal keys never fall back to platform keys. Passwords use bcrypt hashing (12 salt rounds), and JWT sessions utilize per-user token versions for instant multi-device revocation. Automated crash reporting sanitizes all logs by recursively stripping JWT tokens, authorization headers, cookies, API keys, bank account numbers, and email addresses. Full GDPR/DPDP data sovereignty includes self-service account closure (cascading purge of all statements, transactions, files, and chat history with anonymized SHA-256 cryptographic audit logs) and comprehensive user data exports in machine-readable JSON archives and multi-page vector PDF ledger reports.',
  preferencesAndI18n:
    'Finlytix supports multi-currency display (INR, USD, EUR, GBP, AED, SGD, CAD, AUD, JPY), 12 regional and international languages (English, Hindi, Tamil, Telugu, Bengali, Marathi, Gujarati, Kannada, Malayalam, Spanish, French, German), user-configurable date formats (DD/MM/YYYY, MM/DD/YYYY, YYYY-MM-DD, DD MMM YYYY, MMM DD, YYYY), and 12h/24h time formats across web and mobile. Custom date range pickers allow flexible month, quarter, year, and custom interval filtering.',
  limits:
    'Do not describe unimplemented features as available. While iOS & Android mobile apps, WhatsApp statement ingestion & chat copilot, BYOK encryption, cost transparency, and multi-format data exports are fully implemented and live, Finlytix still has: No refund management, live account balances, automatic bank feeds, guaranteed fraud detection, or investment recommendations. For missing statements, ask for the intended period and compare actual coverage; absence alone does not prove a missing statement.',
};
